package cc.monomer.metricflow.domain.manifest.validation.rules

import cc.monomer.metricflow.domain.manifest.model.SemanticManifest
import cc.monomer.metricflow.domain.manifest.model.enums.SemanticManifestNodeType
import cc.monomer.metricflow.domain.manifest.model.enums.TimeGranularity
import cc.monomer.metricflow.domain.manifest.model.references.ElementReference
import cc.monomer.metricflow.domain.manifest.model.references.SemanticModelElementReference
import cc.monomer.metricflow.domain.manifest.validation.FileContext
import cc.monomer.metricflow.domain.manifest.validation.SemanticManifestValidationRule
import cc.monomer.metricflow.domain.manifest.validation.SemanticModelElementContext
import cc.monomer.metricflow.domain.manifest.validation.SemanticModelElementType
import cc.monomer.metricflow.domain.manifest.validation.ValidationContext
import cc.monomer.metricflow.domain.manifest.validation.ValidationError
import cc.monomer.metricflow.domain.manifest.validation.ValidationIssue
import cc.monomer.metricflow.domain.manifest.validation.ValidationIssueContext

/**
 * Checks that names of elements (measures, dimensions, entities) within a semantic model are
 * unique and use the canonical character set, and that top-level objects (semantic models,
 * metrics, saved queries, custom granularities) likewise have unique valid names.
 *
 * Port of `metricflow_semantic_interfaces/validations/unique_valid_name.py::UniqueAndValidNameRule`.
 */
object UniqueAndValidNameRule : SemanticManifestValidationRule {
    /**
     * Valid-name regex: start with lowercase letter, only lowercase + digits + underscores,
     * no `__` dunders, end with lowercase letter or digit, at least 2 chars long.
     */
    private val NAME_REGEX: Regex =
        Regex("\\A[a-z]((?!__)[a-z0-9_])*[a-z0-9]\\Z")

    /** MetricFlow's own reserved keywords. Port of `MetricFlowReservedKeywords`. */
    private val METRICFLOW_RESERVED_KEYWORDS: Map<String, String> = mapOf(
        "metric_time" to "Used as the query input for creating time series metrics from measures with " +
            "different time dimension names.",
        "mf_internal_uuid" to "Used internally to reference a column that has a uuid generated by MetricFlow.",
    )

    /**
     * Public helper: check a single name. Mirrors Python's `check_valid_name`.
     */
    fun checkValidName(name: String, context: ValidationContext?): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        if (!NAME_REGEX.matches(name)) {
            issues.add(
                ValidationError(
                    context = context,
                    message = "Invalid name `$name` - names may only contain lower case letters, numbers, " +
                        "and underscores. Additionally, names must start with a lower case letter, cannot end " +
                        "with an underscore, cannot contain dunders (double underscores, or __), and must be " +
                        "at least 2 characters long.",
                ),
            )
        }
        val timeGranNames = TimeGranularity.entries.map { it.name }
        if (name.uppercase() in timeGranNames) {
            issues.add(
                ValidationError(
                    context = context,
                    message = "Invalid name `$name` - names cannot match reserved time granularity keywords " +
                        "($timeGranNames)",
                ),
            )
        }
        val reason = METRICFLOW_RESERVED_KEYWORDS[name.lowercase()]
        if (reason != null) {
            issues.add(
                ValidationError(
                    context = context,
                    message = "Invalid name `$name` - this name is reserved by MetricFlow. Reason: $reason",
                ),
            )
        }
        return issues
    }

    override fun validateManifest(semanticManifest: SemanticManifest): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        issues.addAll(validateTopLevelObjects(semanticManifest))
        issues.addAll(validateSemanticModelElementsAndTimeSpines(semanticManifest))
        return issues
    }

    private fun validateTopLevelObjects(semanticManifest: SemanticManifest): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        issues.addAll(
            validateTopLevelObjectsOfType(
                semanticManifest.semanticModels.map { it.name to it.metadata },
                SemanticManifestNodeType.SEMANTIC_MODEL,
            ),
        )
        issues.addAll(
            validateTopLevelObjectsOfType(
                semanticManifest.metrics.map { it.name to it.metadata },
                SemanticManifestNodeType.METRIC,
            ),
        )
        issues.addAll(
            validateTopLevelObjectsOfType(
                semanticManifest.savedQueries.map { it.name to it.metadata },
                SemanticManifestNodeType.SAVED_QUERY,
            ),
        )
        return issues
    }

    private fun validateTopLevelObjectsOfType(
        objects: List<Pair<String, cc.monomer.metricflow.domain.manifest.model.Metadata?>>,
        objectType: SemanticManifestNodeType,
    ): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        val seen = mutableSetOf<String>()
        // Mirror Python's enum repr: `SemanticManifestNodeType.METRIC`.
        val nodeTypeRepr = "SemanticManifestNodeType.${objectType.name}"
        for ((name, metadata) in objects) {
            val ctx = ValidationIssueContext(
                fileContext = FileContext.fromMetadata(metadata),
                objectName = name,
                objectType = objectType.value,
            )
            issues.addAll(checkValidName(name, ctx))
            if (name in seen) {
                issues.add(
                    ValidationError(
                        context = ctx,
                        message = "Can't use name `$name` for a $nodeTypeRepr when it was already " +
                            "used for another $nodeTypeRepr",
                    ),
                )
            } else {
                seen.add(name)
            }
        }
        return issues
    }

    private fun validateSemanticModelElementsAndTimeSpines(
        semanticManifest: SemanticManifest,
    ): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        val customGranRestrictedNamesAndTypes = mutableMapOf<String, String>()

        for (semanticModel in semanticManifest.semanticModels) {
            data class Info(val reference: ElementReference, val type: String, val ctx: ValidationContext)
            val tuples = mutableListOf<Info>()
            for (measure in semanticModel.measures) {
                customGranRestrictedNamesAndTypes[measure.name] = SemanticModelElementType.MEASURE.value
                tuples.add(
                    Info(
                        reference = measure.reference,
                        type = "measure",
                        ctx = SemanticModelElementContext(
                            fileContext = FileContext.fromMetadata(semanticModel.metadata),
                            semanticModelElement = SemanticModelElementReference(
                                semanticModelName = semanticModel.name,
                                elementName = measure.name,
                            ),
                            elementType = SemanticModelElementType.MEASURE,
                        ),
                    ),
                )
            }
            for (entity in semanticModel.entities) {
                customGranRestrictedNamesAndTypes[entity.name] = SemanticModelElementType.ENTITY.value
                tuples.add(
                    Info(
                        reference = entity.reference,
                        type = "entity",
                        ctx = SemanticModelElementContext(
                            fileContext = FileContext.fromMetadata(semanticModel.metadata),
                            semanticModelElement = SemanticModelElementReference(
                                semanticModelName = semanticModel.name,
                                elementName = entity.name,
                            ),
                            elementType = SemanticModelElementType.ENTITY,
                        ),
                    ),
                )
            }
            for (dimension in semanticModel.dimensions) {
                customGranRestrictedNamesAndTypes[dimension.name] = SemanticModelElementType.DIMENSION.value
                tuples.add(
                    Info(
                        reference = dimension.reference,
                        type = "dimension",
                        ctx = SemanticModelElementContext(
                            fileContext = FileContext.fromMetadata(semanticModel.metadata),
                            semanticModelElement = SemanticModelElementReference(
                                semanticModelName = semanticModel.name,
                                elementName = dimension.name,
                            ),
                            elementType = SemanticModelElementType.DIMENSION,
                        ),
                    ),
                )
            }

            val refToType = mutableMapOf<String, String>()
            for (info in tuples) {
                val key = info.reference.elementName
                val existing = refToType[key]
                if (existing != null) {
                    issues.add(
                        ValidationError(
                            context = info.ctx,
                            message = "In semantic model `${semanticModel.name}`, can't use name " +
                                "`$key` for a ${info.type} when it was already used for a " +
                                "$existing",
                        ),
                    )
                } else {
                    refToType[key] = info.type
                }
            }
            for (info in tuples) {
                issues.addAll(checkValidName(info.reference.elementName, info.ctx))
            }
        }

        // Add metric + semantic model names to the restricted set
        for (metric in semanticManifest.metrics) {
            customGranRestrictedNamesAndTypes[metric.name] = SemanticManifestNodeType.METRIC.value
        }
        for (semanticModel in semanticManifest.semanticModels) {
            customGranRestrictedNamesAndTypes[semanticModel.name] = SemanticManifestNodeType.SEMANTIC_MODEL.value
        }

        val seenCustomGranNames = mutableSetOf<String>()
        val duplicateCustomGranNames = mutableSetOf<String>()
        var lastTimeSpineContext: ValidationContext? = null
        for (timeSpine in semanticManifest.projectConfiguration.timeSpines) {
            val ctx = ValidationIssueContext(
                fileContext = FileContext(),
                objectName = timeSpine.nodeRelation.alias,
                objectType = SemanticManifestNodeType.TIME_SPINE.value,
            )
            lastTimeSpineContext = ctx
            for (cg in timeSpine.customGranularities) {
                issues.addAll(checkValidName(cg.name, ctx))
                val restrictedType = customGranRestrictedNamesAndTypes[cg.name]
                if (restrictedType != null) {
                    issues.add(
                        ValidationError(
                            context = ctx,
                            message = "Can't use name `${cg.name}` for a custom granularity when it was " +
                                "already used for a $restrictedType.",
                        ),
                    )
                }
                if (cg.name in seenCustomGranNames) {
                    duplicateCustomGranNames.add(cg.name)
                }
                seenCustomGranNames.add(cg.name)
            }
        }
        if (duplicateCustomGranNames.isNotEmpty()) {
            issues.add(
                ValidationError(
                    context = lastTimeSpineContext,
                    message = "Custom granularity names must be unique, but found duplicate custom granularities with " +
                        "the names $duplicateCustomGranNames.",
                ),
            )
        }
        return issues
    }

}
