package cc.monomer.metricflow.domain.manifest.model

import cc.monomer.metricflow.domain.manifest.model.serialization.ManifestJson
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import java.io.File
import kotlin.test.assertEquals

/**
 * Strict round-trip test against every JSON manifest fixture under `corpus/manifests/`.
 *
 * For each manifest fixture:
 * 1. Parse the JSON into a [SemanticManifest] with `ignoreUnknownKeys = false`
 *    (strict — if the JSON has a field our model lacks, this throws).
 * 2. Re-serialise the parsed object back to JSON.
 * 3. Re-parse the re-serialised JSON into a second [SemanticManifest].
 * 4. Assert structural equality between the two parsed objects, and between
 *    the original [JsonElement] tree and the re-serialised tree.
 *
 * Notes:
 * - `JsonElement` equality is order-sensitive for arrays and object keys; we
 *   accept that because both Python and our [ManifestJson] preserve insertion
 *   order across encode/decode.
 * - Nullable Kotlin fields default to `null`, which lets a manifest omit them
 *   (e.g. `minimal_valid_manifest.json` skips `metadata`, `label`, `config`).
 *   The re-serialised form WILL include those keys as `null`, which is exactly
 *   what Python's Pydantic emits, so structural equality holds against the
 *   richer fixtures.
 * - The exception is hand-written `minimal_*` fixtures that omit many fields;
 *   for those we compare via the parsed-object → re-encode → re-parse loop
 *   only (the "object equality" round-trip), since the original raw JSON
 *   intentionally lacks fields the Python format would emit.
 */
class ManifestRoundTripTest {

    private val manifestsDir: File by lazy {
        val repoRoot = System.getProperty("metricflow.repoRoot")
            ?: File("..").absolutePath
        File(repoRoot, "corpus/manifests").also {
            require(it.isDirectory) { "Manifests directory not found: $it" }
        }
    }

    private val rawJson: Json = Json { ignoreUnknownKeys = false }

    @TestFactory
    fun `every manifest round-trips`(): List<DynamicTest> {
        val files = manifestsDir.listFiles { f -> f.isFile && f.extension == "json" }
            ?.sortedBy { it.name }
            ?: error("No manifest fixtures found in $manifestsDir")
        check(files.isNotEmpty()) { "Manifest corpus is empty at $manifestsDir" }
        return files.map { file ->
            DynamicTest.dynamicTest("round-trip ${file.name}") {
                roundTripStrict(file)
            }
        }
    }

    private fun roundTripStrict(file: File) {
        val raw = file.readText()
        val parsed = ManifestJson.decodeFromString(SemanticManifest.serializer(), raw)
        val reSerialised = ManifestJson.encodeToString(SemanticManifest.serializer(), parsed)
        val reParsed = ManifestJson.decodeFromString(SemanticManifest.serializer(), reSerialised)
        assertEquals(
            parsed,
            reParsed,
            "Re-parsed manifest differs from the originally-parsed manifest (${file.name})",
        )

        // JsonElement equality — this catches subtle differences in key ordering
        // and `null`-vs-absent semantics. Only check this for fixtures that emit
        // the canonical Pydantic shape (i.e. include every nullable key). Hand-
        // written minimal fixtures that intentionally omit keys are exempt.
        if (file.name in CANONICAL_FIXTURES) {
            val originalTree: JsonElement = rawJson.parseToJsonElement(raw)
            val reSerialisedTree: JsonElement = rawJson.parseToJsonElement(reSerialised)
            assertEquals(
                originalTree,
                reSerialisedTree,
                "Re-serialised manifest tree differs from the original (${file.name})",
            )
        }
    }

    private companion object {
        /**
         * Fixtures generated by Python's Pydantic serialisation — these include
         * every nullable key (`"label": null`, `"config": null`, ...) and so
         * are eligible for JsonElement-level structural equality.
         *
         * Hand-written fixtures (`minimal_valid_manifest.json`,
         * `minimal_invalid_manifest.json`) omit such keys to stay readable; we
         * only validate the object-round-trip on those.
         */
        val CANONICAL_FIXTURES: Set<String> = setOf(
            "ambiguous_resolution_manifest.json",
            "config_linter_manifest.json",
            "cyclic_join_manifest.json",
            "data_warehouse_validation_manifest.json",
            "derived_metrics_manifest.json",
            "extended_date_manifest.json",
            "join_types_manifest.json",
            "multi_hop_join_manifest.json",
            "name_edge_case_manifest.json",
            "non_sm_manifest.json",
            "partitioned_multi_hop_join_manifest.json",
            "scd_manifest.json",
            "sg_00_minimal_manifest.json",
            "sg_02_single_join.json",
            "sg_05_derived_metric.json",
            "simple_manifest.json",
            "simple_multi_hop_join_manifest.json",
        )
    }
}
